trigger:
  branches:
    include:
      - main  # Specify the branch to trigger deployment

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  # Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Specify the .NET version you're using

  # Restore dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'Simukai_Part3.csproj'

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'Simukai_Part3.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Run tests
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'Simukai_Part3.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Publish the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'Simukai_Part3.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'


  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'YourAzureSubscription' 
      appType: 'webApp'
      appName: 'YourAppServiceName'  # Replace with your Azure App Service name
      package: '$(Build.ArtifactStagingDirectory)/Simukai_Part3.zip'
